### ISSUE TITLE
Proposal: remove word "sport" from objectives motion

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-documents#107]
The Objectives motion 1.1 reads "To act as the world governing body for the sport of Speedcubing". Without wanting to weigh in on whether or not cubing is a sport or not, I'd prefer to not explicitly state it as such.

My reasoning is purely financial; in Australia we already have quite high public liability insurance coats, and these would increase dramatically if Speedcubing Australia were to be classified as organising sport.

**Comment by cubewhiz** [comment]
Hi Ed,

Doesn't Speedcubing Australia choose its own classification as an organization? Does this motion affect your events?

**Comment by EdHollingdale** [comment]
The issue is that the insurance is not about the type of organisation we
are, but rather the type of events we run. We have insurance for
competitons we organise, and say that these competitons are not sporting
events and do not involve sport (which I maintain is true). Yet they are
sanctioned by another organisation that says it governs a sport.

**Comment by cubewhiz** [comment]
Up until a day or two ago, this sounded completely reasonable, but we were contacted by a different regional organization that asked us to CONFIRM that the WCA is a sports organization because it meant that they could receive additional funding from their local government. Without debating on whether speedcubing is or should be considered a sport, it's not clear to me which distinction would be better overall for the WCA and regional organizations.

**Comment by cubewhiz** [comment]
As per our most recent Board meeting, the Board is actually in favor of recognizing speedcubing as a sport. I'm closing this for now.
