### ISSUE TITLE
WCRP, Universal Registration Requirements

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#112]
This was shortly mentioned in the annual staff meeting and seemed to have great support. WCAT came with the following suggestion: 
> 6.1.3 If the registration requirements are not possible to be fulfilled by an individual due to reasons outside of their control, the Delegate must provide an alternative approach to fulfilling the requirements.
>> 6.1.3.1 Example: A competitor with a credit card not supported by the payment platform may instead be allowed to pay at the venue on the competition day with approval from the Delegate.
>> 6.1.3.2 Example: Not having enough money to pay the registration fee does not qualify for 6.1.3.
>>6.1.3.3 Example: Missing the registration deadline does not qualify for 6.1.3.

Background: Some competitors might not be able to attend a competition due to issues outside of their control.

**Comment by cubewhiz** [comment]
I agree with the principle, but I don't necessarily like the wording. I'd prefer something like:
6.1.3.1 Possible reasons include (but are not limited to) blah blah blah.

and if you think non-examples are important:
6.1.3.2 Exceptions must not be made for x, y, and z.

**Comment by SAuroux** [comment]
I also support the idea behind this, but I see many problems with the current proposal: 

- How can this possibly be a "must"? What if it is beyond the Delegate's control to provide such an alternative? "should" is already obliging unless there is a very good reason against. 
- Why the Delegate? Usually, organizers are handling payments. 
- I don't understand a credit card not supported by the payment platform as _reasons outside of their control_. What prevents the competitor from getting another credit card?

**Comment by DanielEgdal** [comment]
1. Generally I've seen a large portion if Delegates seeing a 'should' and just think "then it doesn't matter". But yes, I can some of your points in this that there might not always be an alternate. Do you have a better alternative? What about 'Must try'?
2. Delegates should know the rules. Maybe changing it to "the organization team or Delegate"? I personally believe a Delegate should be aware whenever such circumstances arise.
3. If you go to a competition in Russia, you would need to acquire a Russian credit card to pay the fee with their current system. I'm not too sure how it works in all countries, but I could see this being the issue in other countries, e.g. in SA I've heard that making transfers to standard accounts being an issue from Delegates, therefore some have already now started making exceptions in their registration requirements.

**Comment by SAuroux** [comment]
1. I am aware of that, but this is an educational problem that should be fixed instead of circumvented by using stronger formulations than actually needed. But yes, "must try" or "must attempt" would be fine either I guess.
2. I also think that the delegate should be aware, so why not just require this then?
3. It is pretty clear that this is difficult and eventually needs someone's discretion, so this should probably be included in the wording.

I also noticed that the current wording does not even involve the fact that competitor's are eligible to complete their registration with such an alternative, which is no trivial given that registration requirements often include phrases like "pre-payment required" or "payment via Paypal required".

Here is a suggestion trying to take all of the above into account:

6.1.3 If the registration requirements are not possible to be fulfilled by an individual due to reasons outside of their control, they are eligible for completing their registration following a suitable alternative approach, at the discretion of the Delegate. In case of such an inquiry, organizers must involve the Delegate, who must then carefully assess the individual's situation. If deemed appropriate, Delegate and organizers must make reasonable efforts to provide an alternative approach for the individual to fulfilling the requirements.

**Comment by DanielEgdal** [comment]
Thanks Sébastien! I believe your suggestion makes a lot of sense. Do you think it makes sense to still add the examples and non-examples?

**Comment by SAuroux** [comment]
You're welcome. I am not sure about the examples, but I lean towards yes. I would go with the structure that Bob suggested and focus on the most common examples.

**Comment by cubewhiz** [comment]
Fixed via #117
