### ISSUE TITLE
WCRP, Scorecards

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#115]
Jacob pointed this out, which WCAT agreed with:
> 8.2.2.3 Physical records (e.g. score sheets, written solutions from 3x3x3 Fewest Moves) must be retained for a minimum of 90 days. Digital records (e.g. scramble sequences, results) must be retained for 7 years. Physical records should be kept as long as possible to ensure data accuracy upon any disputes that happen after 90 days.

"Background: WCA has always had some issues due to Delegates not keeping scorecards longer which results in missing data, duplicate data, or incorrect data. This reminder should help them keep records longer which may help reduce these types of incidents."

**Comment by cubewhiz** [comment]
Please see Motion 16.2019.1:
https://www.worldcubeassociation.org/documents/motions/16.2019.1%20-%20Disputes.pdf

Disputes must be filed within 60 days of the act and can be open for up to 60 days beyond that. That decision can be appealed for up to 60 days. In a worst-case scenario, even 180 days should be enough to retain physical records.

Generally, 60 days should be enough (so long as an opened dispute leads to the WRC/WDC asking for the record near the beginning of this process).

Maybe someone can provide me with an example of why a change is necessary here.

**Comment by DanielEgdal** [comment]
I'll let @Jambrose777 comment on it, since he added the point.

**Comment by Jambrose777** [comment]
A change isn't necessary, but this is just a reflection of what really happens. It also doesn't change anything for a Delegate but give them a reminder that keeping scorecards longer can be beneficial.

If a dispute happens after 60 days with probable evidence (take a look at one of the recent explosing fb group's posts) then we should still take it into consideration and have the correct results in our database opposed to results that are known to be bogus. There are some investigations that are opened far after this 60 day period and have resulted in competitors who should have their actual results to be entered as DNF due to the scorecards no longer being available. Theres also a couple cases where WRT has a sanity investigation and the scorecards of competitions forever ago have provided some corrections, or the lack of scorecards makes issues.

I think I've covered the main points. @SAuroux may be able to weigh in if you would like :) (I know this change hasnt come up in WRT)

**Comment by SAuroux** [comment]
If I understand correctly, the only difference to the current document is the last sentence, correct?

If yes, I doubt that this will have a notable impact. Those that keep records longer anyways will just continue doing so, while others that are annoyed by records taking away space will consider this a good reason to still get rid of them after 90 days.

Side note: I think it should say "for a minimum of 7 years" for digital records (analogous to "for a minimum of 90 days").

**Comment by DanielEgdal** [comment]
Based on the arguments on this thread, I will only include the small textual change Sébastien mentioned in the last comment.

**Comment by cubewhiz** [comment]
Fixed via #117
