### ISSUE TITLE
Competition Safety Policy: allow to have combined limit for competitors and guests

### ISSUE THREAD

**Issue by AndreyRadaev** [thewca/wca-documents#195]
Hi! My name is Andrey Radaev. I am organizer of Tyumen Cube Weekend 2020 (31 Oct - 1 Nov, 2020).

Wrote this to correct WCA Competitions Safety Policy. I ask to make possible to introduce combined limit for guests and competitors. This is change to "Return to competitions" 2.1. paragraph. It can be formalized as a new item 2.1.1:

*2.1.1. If the competition has more registrations than the limit, it is possible to increase the participant limit if the organization team can guarantee that the total number of people on the venue does not exceed the limit setted by law or venue.*

I add some info about our competition for argumentation. We have a 50 persons limit for public gatherings. With nowadays Safety Policy we can allow only 25 competitors (a half). But we have a lot of confirmed competitors with a small guests number. I think that limit 35 for our separate competitions will be okay.
1. There are big interest to competition — 44 registrations by 48 hours.
2. We opened an additional form to collect competitors phones. So, we can:
- confirm registration
- talk about an additional information about COVID-19 measures
- confirm if competitor want to bring a guest
3. 25 competitors that fit in limit have only 7 guests
4. Competitors with confirmed registration ask organizers to increase the limit and said that they can came without guests
5. We as organizers can provide all needed protection means: masks, gloves, sanitizers for all competitors and guests. Also we will provide personal pens and measure temperature. All costs are on us, competition are fully free.
6. If we will approve 35 competitors, we will have 35 competitors and 13 guests (summary 48). It is in safety rulesof our region.

Thank you for time you spend to read this. Hope it will be considered.

Stay safe!

**Comment by c-goodyear** [comment]
Hi Andrey,

The way guests and competitors perform and move around a venue are very different. In many countries a guest can be counted as someone who will be sitting, while the competitor will need more square metres.

Additionally, these kinds of cumulative competitor/guest limits could lead to people being pressured into not having a guest with them which is not good for competitors who are minors.

It's best not to rush back into competitions, but ease into them slowly to not add to the problems caused by COVID-19.
