### ISSUE TITLE
Clarification about Regional Organizations

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-documents#208]
The WCA Board has been considering the Regional Organizations role for (mainly) for National-level organizations (see #90). However, it's not that clear in the Bylaws, where the term "regions" is used.  Maybe this should be clarified somewhere?

**Comment by EdHollingdale** [comment]
I think the issue here is that the role of regional organisations in the WCA is increasing, but the current definitions aren't that flexible. Maybe we could add to the rights of ROs the ability to recognise sub-regional organisations (assuming we clarify what a region is) which can in turn have some of the benefits of ROs (like the new wording in the code of conduct).

**Comment by EdHollingdale** [comment]
@thewca/board I believe this issue can be closed as it was resolved when the motions were updated to add sub-ROs.
