### ISSUE TITLE
Naming of staff vs external staff

### ISSUE THREAD

**Issue by jfly** [thewca/wca-documents#24]
(this is slightly related to https://github.com/thewca/wca-documents/issues/23)

I think it's really confusing that "external staff" is not a kind of "staff". This doesn't not feel intuitive to people familiar with English. I'd really love to rename these terms if possible. Here are some proposals:

# Proposal 1

- Rename "staff" to "internal staff"
- Leave "external staff" as "external staff"
- Now, "staff" means "someone who is either an internal staff member or an external staff member"

# Proposal 2

- Leave "staff" as is
- Rename "external staff" to something else. Maybe "consultant" or "external worker" or "external helper"?

**Comment by cubewhiz** [comment]
Does the distinction exist only to define who has voting rights?

**Comment by AlbertoPdRF** [comment]
I need to check the Bylaws and Motions more carefully, because my thought was that this distinguished between members and non-members too, but I saw that there's a subsection in our Bylaws where Non-Voting Membership is introduced and now I'm not sure if External Staff are WCA Members -without voting rights- or not -which I thought was the only way for them to not have voting rights-.

**Comment by AlbertoPdRF** [comment]
I think the best option here is to just have "WCA Staff", and distinguish who has voting rights and who doesn't in the Definitions Motion. I'll send in a PR later with the proposal.
