### ISSUE TITLE
Feedback on Code of Ethics v1.0

### ISSUE THREAD

**Issue by WalkerWelch** [thewca/wca-documents#70]
#67 
Code of Ethics v1.0
#69 
Fix formatting error in Code of Ethics v1.0

Feedback is welcome here for the Code of Ethics. It would be preferred to leave comments and feedback here and not back another issue.
Thank You!

**Comment by EdHollingdale** [comment]
I have some minor problems with 1.2 of the code around Delegates who are also organisers. 1.2 implies that I can only be reimbursed for costs associated with attending as a listed delegate, but not for roles as an organiser (if I am both an organiser and a delegate). I know that this is not the spirit of the code but, for example, if I, as an Organiser, book and pay for a venue would I be ineligible for reimbursement because I am also a listed delegate? Paying for the venue is nothing to do with being a listed delegate for the competition, so it would not be covered. It would be good if 1.2 could be extended to say something along the lines of "as a direct result of attending the competition as a listed Delegate or serving as a competition organiser".

**Comment by WalkerWelch** [comment]
> I have some minor problems with 1.2 of the code around Delegates who are also organisers. 1.2 implies that I can only be reimbursed for costs associated with attending as a listed delegate, but not for roles as an organiser (if I am both an organiser and a delegate). I know that this is not the spirit of the code but, for example, if I, as an Organiser, book and pay for a venue would I be ineligible for reimbursement because I am also a listed delegate? Paying for the venue is nothing to do with being a listed delegate for the competition, so it would not be covered. It would be good if 1.2 could be extended to say something along the lines of "as a direct result of attending the competition as a listed Delegate or serving as a competition organiser".

In this instance you would be acting as organiser when dealing with this competitions cost because it is the organiser's responsibility. Even if you are just the Delegate for the competition and the organizer asks you to help pay the venue cost, you are working with an organisers responsibility. (similar to regulation 1c)

**Comment by Jambrose777** [comment]
Here are concerns I voiced in email last march:

> 1.2.3 When Delegates are not officially listed and are just attending a competition as competitors, their expenses, including registration fees, are not valid for reimbursement.
and 
> 1.3 Registration fees should only be waived for competitors if they perform a role necessary for the running of the competition.

Are a bit contradictory. For instance, if I'm at a competition, and am a non-listed delegate, which means I cannot be reimbursed for the registration fee. However I am going to be one of the hardest working competitors at the competition. But due to 1.2.3 I can't have my fee waived as 1.3 mentions. This is very unfair for delegates who attend competitions they are not listed for.

WEC: "There is a difference between reimbursement and waived. If you are not a listed Delegate (or organizer) for a competition you can still get your registration fee waived as a competition staff member as long as you perform a necessary role in helping the competition."

Me: As far as "staffing" a competitor, either approach can be used to do so. A competitor can be waived upfront or be reimbursed after the competition as a thanks for their work. I don't understand why the two terms are not interchangeable in 1.2.3 and 1.3. If WEC has decided to limit us to doing one or the other, I would much prefer to see the reimbursement route taken for all staff as this would help ensure that they preformed a "necessary role" without having to take a chance.

---

I would like to add a time frame for 1.4.1. For instance we only hold scorecards for 90 days and results for 7 years (with the new competition requirements document).  I don't plan to keep budgets for my competitions forever (as I assume other delegates are the same), so defining a time frame of when a delegate is allowed to dismiss the information would help.

---

> 3.4 Delegates and Organizers should only be officially listed for a competition if they perform a necessary role in the running of the event.

This is the first time we are seeing a definition for what constitutes a listed name on the competition page. I do not agree with this definition. A Delegate can help out tremendously at a competition with making calls helping with any other job needed, however this doesn't make that delegate necessary. The tremendous help goes a long way for a competition, and the delegate should rightfully be listed. The same applies to organizers.
As well, an organizer can preform the necessary role by obtaining the venue, but not help out squat at the competition. This doesn't mean they should be listed.

There were a couple of replies to this; ultimately I feel that necessary is the wrong word and needs further clarification.

---

What do we do about changes in the delegates post competition? If a delegate helped out a significant amount, I'm going to add them as a listed delegate. If they were wearing sponsorship attire, am I no longer allowed to add the delegate?

---

> 4.3 WCA Staff must not promote a third party brand who are not the competition sponsor(s) or sponsors of the WCA, within their role in the WCA.

Does this mean that I cannot wear my company's T-shirt, Nike shoes, Ray ban glasses, Raymond Weil watch, and Denom Jeans to a competition?

WEC: I'd like to point out that this states that you must not "promote" a third party brand. I feel that you wearing these items at a competition is not promotion. As far as I can see there wouldn't be any breaking of the points by just wearing these items.

Me: 4.3 a definition of promote is: further the progress of (something, especially a cause, venture, or aim); support or actively encourage. I would define wearing attire of a company to promote them in some way shape or form. If I wear a coca-cola T-Shirt, I'm supporting the product and further it's progression as others will see me wear the shirt and have coca-cola in their mind.

I think that promote is the wrong word and this point should be refined.

---

Off a snowball of responses:

> It is very standard that nonprofit organizations have conflict of interest policies to make sure the organization is keeping up to that standard. We as the WEC are just trying to make the best decisions to both protect the organization from relatable work with profiting businesses and to allow the sponsored Delegates to keep their sponsorships. This exact thing is even done at CubingUSA Nationals for competition staff members who are sponsored and I have not seen any problems with it then.

I don't see how we can realistically draw comparisons between WCA and other sports organizations or non profits. We have one of the most **unique** sports in the world in which the officials are also competitors and unpaid. At the end of the day, competitors should have a right to be sponsored and its not fair for Delegates to have to do a wardrobe change every 10 minutes because we have to draw very think lines in the sand of when a Delegate is a comeptitor and when they are competing. What they are wearing makes no difference on their ability to do their job.

WEC is asking us to abide by a policy or be removed, yet there is absolutely no benefits the organization is willing to provide to support these threats. We aren't paid, we don't get health insurance, we can't even use the non profit status in any way. These are things that companies give their employees in return for signing say a code of ethics among other things. And ultimately you are telling hard working people providing free labor to get out if they don't agree with the Code of Ethics.

---

> 4.4 WCA Delegates must not wear sponsorship apparel of a personal sponsor during a competition in which they are listed as a Delegate.

Rephrased a bit: For a competition that is sponsored by X, Delegates who are sponsored  by X can’t wear their sponsor clothes due to 4.4 even though delegates who aren’t sponsored can wear clothes from company X.

I’m sorry, but treating someone completely different because they are sponsored (specifically dictating what they can and can’t wear) is not very fair in my eyes. A great example would be if a sponsored by company x delegate and an unsponsored delegate are both listed for a competition where company x is the sponsor. The unsponsored delegate can wear company x short but the sponsored delegate cannot. Again treating these people differently is not okay.

---

So can the registration fees be used for prizes/awards for the winners or to promote the competition/sponsor? This would seem to violate 1.4.3 as those lead to personal profit.
Further, 1.4.3 needs to explicitly mention "Profit from registration fees" as how it currently reads Felipe's concern is very valid in that if I win any prize money and Im a delegate, it must be put into the community. This doesn't seem fair, and doesn't seem like the intention of WEC.

---

> 4.5 Organizers must handle decisions on competition sponsors.

Typically if an organizer fails to do a job (example: printing scorecards), then that responsibility is ultimately up to the delegate. When obtaining a sponsor this is no longer possible without being added as an organizer. In reality, this guideline does absolutely nothing as a delegate can at any point request to be added to the organizational team and then be able to handle sponsorships. This is the only point in which a delegate is forced to list themselves as an organizer in order to do a task.


---

Regarding 6.1 and 6.1.1. Where is the line drawn between my WCA life and my personal life? Am I allowed to be myself on different social media platforms, or am I representing WCA on those as well? I think that defining this line is very important and not crystal clear on where it should be drawn. I certainly would hate to be reported and chastised by WCA for something I've said on social media which I would have defined as outside my WCA role.

**Comment by JonEsparaz** [comment]
> 1.3.3 Competition volunteer application forms should be available for competitions to help
manage and standardize who will be waived for competition volunteer purposes.

_For clarity, my use of "staff" refers to competition volunteers who get their registration fee waived._

Regarding standardization, different Delegates and Organizers will create different application forms, and judge staff applications at their own discretion, so I am unsure of how this creates standardization. Perhaps the WEC should create and distribute a standardized competition volunteer application form to Delegates. This can help determine if applicants of similar merit are being accepted or denied for staff positions consistently.

With the current situation, what can Delegates and Organizers include in application forms? Delegates and Organizers can include legitimate questions in application forms that make their regular staff team the most qualified by default. Example: how many competitions have you staffed? Obviously, the regular staff will have the most experience. As a more extreme example: how many competitions have you staffed under Delegate A? IMO, this is not an acceptable question, but the Code of Ethics does not define what is allowed/disallowed in volunteer application forms. 

At the moment, application forms can help justify selecting the same staff for every competition (which some community members view as an issue).

**Comment by bruchemrfe** [comment]
I normally share my own (!) Delegate Reports (except for private parts) with Competition Organizers. We believe this is valuable for further professional development.
Today I heard that article 2.4 is prohibiting this. Please confirm that this indeed the way that this article is supposed to be.
In think 2.4 needs to be further detailed, because lots of information may be valuable for people we work with. An example: I do not see a reason why I cannot tell someone outside WCA that I am preparing to delegate a competition in Malta.

**Comment by cubewhiz** [comment]
I agree that a Delegate should be able to share his own details about the organization of the competition with the organizers. I don't, however, believe that Incidents should be shared, or that Delegates should be able to share the organization section written by a different delegates (as the language used there may be harsh and negative sometimes, so the Delegate may have worded it differently when speaking directly to the organizers).

**Comment by c-goodyear** [comment]
@Jambrose777 

> Here are concerns I voiced in email last march:
> 
> 1.2.3 When Delegates are not officially listed and are just attending a competition as competitors, their expenses, including registration fees, are not valid for reimbursement.
> and
> 1.3 Registration fees should only be waived for competitors if they perform a role necessary for the running of the competition.
> 
> Are a bit contradictory. For instance, if I'm at a competition, and am a non-listed delegate, which means I cannot be reimbursed for the registration fee. However I am going to be one of the hardest working competitors at the competition. But due to 1.2.3 I can't have my fee waived as 1.3 mentions. This is very unfair for delegates who attend competitions they are not listed for.
> 
> WEC: "There is a difference between reimbursement and waived. If you are not a listed Delegate (or organizer) for a competition you can still get your registration fee waived as a competition staff member as long as you perform a necessary role in helping the competition."
> 
> Me: As far as "staffing" a competitor, either approach can be used to do so. A competitor can be waived upfront or be reimbursed after the competition as a thanks for their work. I don't understand why the two terms are not interchangeable in 1.2.3 and 1.3. If WEC has decided to limit us to doing one or the other, I would much prefer to see the reimbursement route taken for all staff as this would help ensure that they preformed a "necessary role" without having to take a chance.

We think that changing the word "necessary" to "significant" would suffice. Would such a wording change appease your qualms?

> I would like to add a time frame for 1.4.1. For instance we only hold scorecards for 90 days and results for 7 years (with the new competition requirements document). I don't plan to keep budgets for my competitions forever (as I assume other delegates are the same), so defining a time frame of when a delegate is allowed to dismiss the information would help.

I don't see a problem making this 7 years, one of my future aims is to make budgets mandatory so hopefully this point will be irrelevant soon anyway :)

> 3.4 Delegates and Organizers should only be officially listed for a competition if they perform a necessary role in the running of the event.
> 
> This is the first time we are seeing a definition for what constitutes a listed name on the competition page. I do not agree with this definition. A Delegate can help out tremendously at a competition with making calls helping with any other job needed, however this doesn't make that delegate necessary. The tremendous help goes a long way for a competition, and the delegate should rightfully be listed. The same applies to organizers.
> As well, an organizer can preform the necessary role by obtaining the venue, but not help out squat at the competition. This doesn't mean they should be listed.
> 
> There were a couple of replies to this; ultimately I feel that necessary is the wrong word and needs further clarification.

As above, I hope that the change to "significant" is acceptable and provides the flexibility that is needed in some regions.

>What do we do about changes in the delegates post competition? If a delegate helped out a significant amount, I'm going to add them as a listed delegate. If they were wearing sponsorship attire, am I no longer allowed to add the delegate?

Unless they made a ruling only allowed to be made by a Delegate, this would just make them be a helpful competitor!

Regarding all the points about third party branding, this is obviously not the intent of what we wrote and your examples of Nike and Ray-Bans make a good point. These can not be reasonably interpreted as an affiliation with the WCA as a sponsorship.

> > 4.4 WCA Delegates must not wear sponsorship apparel of a personal sponsor during a competition in which they are listed as a Delegate.
> 
> Rephrased a bit: For a competition that is sponsored by X, Delegates who are sponsored by X can’t wear their sponsor clothes due to 4.4 even though delegates who aren’t sponsored can wear clothes from company X.
> 
> I’m sorry, but treating someone completely different because they are sponsored (specifically dictating what they can and can’t wear) is not very fair in my eyes. A great example would be if a sponsored by company x delegate and an unsponsored delegate are both listed for a competition where company x is the sponsor. The unsponsored delegate can wear company x short but the sponsored delegate cannot. Again treating these people differently is not okay.

Thanks for pointing out the loophole that Delegates who are not sponsored as competitors actually *could* wear apparel that appears the same as a Delegate who is a sponsored competitor! We will close this and enforce a more strict and consistent process among Delegates with or without personal sponsors regardless of their listing, given that public perception of their attire can be influential to newcomers.

> So can the registration fees be used for prizes/awards for the winners or to promote the competition/sponsor? This would seem to violate 1.4.3 as those lead to personal profit.
> Further, 1.4.3 needs to explicitly mention "Profit from registration fees" as how it currently reads Felipe's concern is very valid in that if I win any prize money and Im a delegate, it must be put into the community. This doesn't seem fair, and doesn't seem like the intention of WEC.

1.4.3 can not only be limited to registration fees since it would also need to include money obtained from sponsors of a competition etc.
If you win prize money, that is from being a competitor, not a Delegate so WEC would have no scope to tell you what to do with that money.

> >4.5 Organizers must handle decisions on competition sponsors.
> 
> Typically if an organizer fails to do a job (example: printing scorecards), then that responsibility is ultimately up to the delegate. When obtaining a sponsor this is no longer possible without being added as an organizer. In reality, this guideline does absolutely nothing as a delegate can at any point request to be added to the organizational team and then be able to handle sponsorships. This is the only point in which a delegate is forced to list themselves as an organizer in order to do a task.

I don't see the equivelance between printing scorecards and obtaining a sponsor. One of these is necessary for a competition to function, the other is not. If a sponsor *is* necessary in a case, then it should have been determined and dealt with before the competition is announced (this also gives the sponsor maximal visibility which is what most of them want...)
You wouldn't have to be added to the organizing team anyway, if an Organizer says to you "Jacob, I would like "Cube Store X" to sponsor this competition, that is them making the decision. I think that would constitute enough grounds for you to proceed with contacting them in such a case if the Organizer failed to do so.

> Regarding 6.1 and 6.1.1. Where is the line drawn between my WCA life and my personal life? Am I allowed to be myself on different social media platforms, or am I representing WCA on those as well? I think that defining this line is very important and not crystal clear on where it should be drawn. I certainly would hate to be reported and chastised by WCA for something I've said on social media which I would have defined as outside my WCA role.

I would also define social media as being outside a WCA role. The upcoming Code of Conduct will seek to draw that line more clearly, however WEC will not be investigating any Facebook posts Staff make.

**Comment by c-goodyear** [comment]
@bruchemrfe 

As you know, we have had some issues with Delegates forwarding mails to Organizers. Therefore I have proposed changing the relevant sections to:
2.4. All work done within the WCA is confidential and must not be disclosed to non-WCA Staff members without explicit permission from relevant members.
   2.4.1. Delegates may provide relevant feedback to the Organizers but must not give visibility of incidents, or sections written by other Delegates.

**Comment by c-goodyear** [comment]
@JonEsparaz this is something I hope we will be able to have WQAC create since it is more within their scope as a document than ours!

**Comment by cubewhiz** [comment]
Version 2.0 was released in November 2019. If there is any feedback on the Code of Ethics v2.0, please open a new thread.
